### Request Access Token for TEST_CLIENT (grant_type=client_credentials)

POST {{authorization}}/oauth/token?grant_type=client_credentials
Content-Type: application/json
Authorization: Basic {{basicAuth}} # base64 encoded client_id:client_secret

> {%
    if(response.body["access_token"]) {
      client.global.set("accessToken", response.body.access_token);
    }
%}

### Request Access Token for TEST_USER (grant_type=password)
POST {{authorization}}/oauth/token?grant_type=password&username={{username}}&password={{password}}
Content-Type: application/json
Authorization: Basic {{basicAuth}} # base64 encoded client_id:client_secret

> {%
    if(response.body["access_token"]) {
      client.global.set("accessToken", response.body.access_token);
    }

    if(response.body["refresh_token"]) {
      client.global.set("refreshToken", response.body.refresh_token);
    }
%}

### Refresh Access Token for TEST_USER (grant_type=refresh_token)

POST {{authorization}}/oauth/token?grant_type=refresh_token&refresh_token={{refreshToken}}
Content-Type: application/json
Authorization: Basic {{basicAuth}} # base64 encoded client_id:client_secret

> {%
    if(response.body["access_token"]) {
      client.global.set("accessToken", response.body.access_token);
    }

    if(response.body["refresh_token"]) {
      client.global.set("refreshToken", response.body.refresh_token);
    }
%}
